### ISSUE TITLE
Cofree instances are very wrong

### ISSUE THREAD

**Issue by ekmett** [ekmett/comonad#17]
The ComonadApply and Apply don't agree with the Applicative for Cofree.

There are two structures here. One tries to zip together the 'f's stream-style. The other works with an indexed-monoid style to smash the 'f's together. These need to split into separate (co)monads.

**Comment by fumieval** [comment]
Is the `(<@>) = (<*>)` requirement really necessary? They don't seem to conflict if we just remove this restriction (but the mathematical symmetry will be gone, though).

**Comment by ekmett** [comment]
`(<@>) = (<*>)` could be relaxed, if I could swallow my gorge, but `(<.>) = (<*>)` is a hard requirement.

**Comment by glguy** [comment]
This issue is currently tracked in its own repository https://github.com/ekmett/free/issues/36
