### ISSUE TITLE
Build with GHC-7.2.2 fails because of SafeHaskell

### ISSUE THREAD

**Issue by phadej** [ekmett/comonad#41]
```
src/Control/Comonad/Store/Class.hs:32:1:
    semigroups-0.18.3:Data.Semigroup can't be safely imported! The package (semigroups-0.18.3) the module resides in isn't trusted.
```

*EDIT* It might be easier to drop GHC-7.2 support than try to figure  SafeHaskell issues with it, IIRC there were others in the past too, `lens` doesn't build with 7.2 anymore (due `call-stack`, at least).

**Comment by phadej** [comment]
Also, there is install plan with `tagged-0.1.0` for GHC-7.8.4 resulting into

```
src/Control/Comonad.hs:59:1:
    Data.Tagged: Can't be safely imported!
    The module itself isn't safe.
```

(with ghc-7.6 it compiles fine with `tagged-0.1.0`)

**Comment by RyanGlScott** [comment]
As far as https://github.com/ekmett/comonad/issues/41#issue-286733389 goes, that's a `Cabal` bug that I've filed upstream at https://github.com/haskell/cabal/issues/5010.

As far as https://github.com/ekmett/comonad/issues/41#issuecomment-355969643, should we make a revision requiring `tagged >= 0.7.0`?

**Comment by phadej** [comment]
matrix with `--constraint==tagged-0.1` has some red:

![screenshot from 2018-01-09 12-03-22](https://user-images.githubusercontent.com/51087/34717815-fe089660-f53c-11e7-8303-f7bc38bbfee0.png)

- `tagged-0.7` was released on Wed Aug 14 05:17:03 UTC 2013 by
- `comonad-3.1` was released on Fri Jul 12 19:35:03 UTC 2013
- GHC-7.10.1 on 27 March 2015, GHC-7.8.1 on 9 April 2014

with `tagged==0.7.*' constraint matrix is green:

![screenshot from 2018-01-09 12-33-45](https://user-images.githubusercontent.com/51087/34717952-7fc06552-f53d-11e7-8676-fe7efce30dc0.png)

I'd make revisions with `tagged >= 0.7` lower bound for versions red in the first matrix picture.

---

I run some checks on `comonad-3.1` and `comonad-4.0`:  and the new bound doesn't force anything else up or down, and other lower bounds on these versions seems correct.

---

[Stackage-LTS-0.0](https://www.stackage.org/lts-0.0) has `tagged-0.7.3` (and `comonad-4.2.2`) so Stackage won't be affected by revisions

**Comment by RyanGlScott** [comment]
@phadej has made the necessary revisions on Hackage.

The remaining issue (https://github.com/haskell/cabal/issues/5010) pretty much has to be fixed on `Cabal`'s end, it seems, so I don't think there's anything more that can be done here. (I've already set the 7.2.2 Travis matrix entry to allow failures.)

Closing.

**Comment by RyanGlScott** [comment]
For the record, I've worked around this issue in the [`comonad-5.0.3`](http://hackage.haskell.org/package/comonad-5.0.3) release.
